# Generated by Django 3.2.9 on 2021-11-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='logoUrl',
            field=models.URLField(null=True),
        ),
    ]
