# Generated by Django 3.2.9 on 2021-12-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_source_logourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='locale',
            field=models.CharField(default='fr-BE', max_length=10),
        ),
    ]
