# Generated by Django 3.2.9 on 2022-01-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_source_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.TextField()),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('gender', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
    ]
