# Generated by Django 3.2.9 on 2021-12-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_releasenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasenote',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
